### ISSUE TITLE
no-invalid-state-props doesn't allow exit at the root

### ISSUE THREAD

**Issue by tivac** [rlaffers/eslint-plugin-xstate#17]
**Describe the bug**
`exit` actions on the root of a state machine are flagged by the `no-invalid-state-props` rule, but they work exactly as expected when the machine is run using `invoke` from a parent machine so I don't think they should be marked as an error?

**Expected behavior**
`exit` actions on the root of a machine are allowed by the rule.

**Actual behavior**
`exit` actions on the root of the machine are flagged as invalid.

**Versions (please complete the following information):**
 - Node version: 16.20.0
 - ESLint version: 8.46.0
 - eslint-plugin-xstate version: 1.1.1

**Additional context**
https://stackblitz.com/edit/eslint-plugin-xstate-exit-at-root?file=statechart.js

Use `npm run lint` in the terminal pane to see the rule incorrectly match.

**Comment by rlaffers** [comment]
Thanks for the report, this will be fixed shortly.
