### ISSUE TITLE
no-ondone-outside-compound-state triggers for invoke with arrays

### ISSUE THREAD

**Issue by tivac** [rlaffers/eslint-plugin-xstate#18]
**Describe the bug**
If you specify an `invoke` property in xstate using an array of things to invoke, and one of those has an `onDone` property, the `no-ondone-outside-compound-state` rule will trigger on it and claim it's invalid.

**Expected behavior**
The `onDone` is fine, because it works fine in xstate and is correct usage.

**Actual behavior**
A false positive match that fails linting.

**Versions (please complete the following information):**
 - Node version: 16.20.0
 - ESLint version: 8.46.0
 - eslint-plugin-xstate version: 1.1.1

**Additional context**
https://stackblitz.com/edit/eslint-plugin-xstate-invoke-array-ondone?file=statechart.js

Use `npm run lint` in the terminal pane to see the rule incorrectly match.

**Comment by rlaffers** [comment]
Thanks for the report, will be fixed shortly.
